version: "2"

run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused
    - misspell
    - copyloopvar
  exclusions:
    paths:
      - internal/ui  # skip: //go:embed dist/* needs dist from build
    rules:
      - path: '.*test.*\.go'
        linters:
          - bodyclose
          - errcheck

