version: "2"

run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused
    - misspell
    - copyloopvar

issues:
  exclude-use-default: false
  exclude-rules:
    - path: '.*test.*\.go'
      linters:
        - bodyclose
        - errcheck

