# GoReleaser config: cross-platform binaries, Docker, GitHub Releases, SBOM.
# Local snapshot: goreleaser release --snapshot --clean
# Release: push tag v* to trigger release workflow.

version: 2

project_name: agentary

# Binaries: Linux (all distros), macOS (Intel + Apple Silicon), Windows (x64 + ARM64).
builds:
  - id: agentary
    main: ./cmd/agentary
    binary: agentary
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux   # All Linux distros (amd64 + arm64)
      - darwin  # macOS Intel (amd64) + Apple Silicon M1/M2/M3 (arm64)
      - windows # Windows x64 (amd64) + Windows on ARM (arm64)
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    builds:
      - agentary

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  groups:
    - title: Features
      regexp: "^feat"
    - title: Bug Fixes
      regexp: "^fix"
    - title: Performance
      regexp: "^perf"
    - title: Documentation
      regexp: "^docs"
    - title: Other
      order: 999
  filters:
    exclude:
      - "^chore:"
      - "^test:"
      - "^ci:"

release:
  github:
    owner: ankittk
    name: agentary
  draft: false
  prerelease: auto
  name_template: "{{ .Tag }}"
  extra_files:
    - glob: checksums.txt

# Docker: single image for linux/amd64 (primary). Multi-arch can be added via docker_manifests.
dockers:
  - image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/agentary:{{ .Version }}"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/agentary:latest"
    use: buildx
    dockerfile: Dockerfile
    goos: linux
    goarch: amd64

# SBOM for archive artifacts (binaries). Requires syft in PATH on release runner.
sboms:
  - id: archive-sbom
    artifacts: archive
    documents:
      - "${artifact}.spdx.json"
    cmd: syft
    args:
      - "${artifact}"
      - "-o"
      - "spdx-json=${document}"
      - "--quiet"
