ALTER TABLE tasks ADD COLUMN IF NOT EXISTS worktree_path TEXT;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS branch_name TEXT;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS base_sha TEXT;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS repo_name TEXT;
