// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: proto/agentary/v1/runtime.proto

package pbruntime

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TurnRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Team             string                 `protobuf:"bytes,1,opt,name=team,proto3" json:"team,omitempty"`
	Agent            string                 `protobuf:"bytes,2,opt,name=agent,proto3" json:"agent,omitempty"`
	TaskId           *int64                 `protobuf:"varint,3,opt,name=task_id,json=taskId,proto3,oneof" json:"task_id,omitempty"`
	Input            string                 `protobuf:"bytes,4,opt,name=input,proto3" json:"input,omitempty"`
	NetworkAllowlist []string               `protobuf:"bytes,5,rep,name=network_allowlist,json=networkAllowlist,proto3" json:"network_allowlist,omitempty"`
	Model            string                 `protobuf:"bytes,6,opt,name=model,proto3" json:"model,omitempty"`                           // e.g. claude-sonnet; optional from agent config
	MaxTokens        int32                  `protobuf:"varint,7,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"` // 0 = use default
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TurnRequest) Reset() {
	*x = TurnRequest{}
	mi := &file_proto_agentary_v1_runtime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TurnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TurnRequest) ProtoMessage() {}

func (x *TurnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentary_v1_runtime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TurnRequest.ProtoReflect.Descriptor instead.
func (*TurnRequest) Descriptor() ([]byte, []int) {
	return file_proto_agentary_v1_runtime_proto_rawDescGZIP(), []int{0}
}

func (x *TurnRequest) GetTeam() string {
	if x != nil {
		return x.Team
	}
	return ""
}

func (x *TurnRequest) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *TurnRequest) GetTaskId() int64 {
	if x != nil && x.TaskId != nil {
		return *x.TaskId
	}
	return 0
}

func (x *TurnRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *TurnRequest) GetNetworkAllowlist() []string {
	if x != nil {
		return x.NetworkAllowlist
	}
	return nil
}

func (x *TurnRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *TurnRequest) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // e.g. turn_started, agent_activity, turn_ended
	Team          string                 `protobuf:"bytes,2,opt,name=team,proto3" json:"team,omitempty"`
	Agent         string                 `protobuf:"bytes,3,opt,name=agent,proto3" json:"agent,omitempty"`
	TaskId        *int64                 `protobuf:"varint,4,opt,name=task_id,json=taskId,proto3,oneof" json:"task_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Data          *structpb.Struct       `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"` // optional JSON-like payload
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_proto_agentary_v1_runtime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentary_v1_runtime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_agentary_v1_runtime_proto_rawDescGZIP(), []int{1}
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetTeam() string {
	if x != nil {
		return x.Team
	}
	return ""
}

func (x *Event) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *Event) GetTaskId() int64 {
	if x != nil && x.TaskId != nil {
		return *x.TaskId
	}
	return 0
}

func (x *Event) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Event) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

type TurnResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        string                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"` // outcome string (e.g. done, submit_for_review, changes_requested)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TurnResult) Reset() {
	*x = TurnResult{}
	mi := &file_proto_agentary_v1_runtime_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TurnResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TurnResult) ProtoMessage() {}

func (x *TurnResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentary_v1_runtime_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TurnResult.ProtoReflect.Descriptor instead.
func (*TurnResult) Descriptor() ([]byte, []int) {
	return file_proto_agentary_v1_runtime_proto_rawDescGZIP(), []int{2}
}

func (x *TurnResult) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

// RunTurnResponse is a single stream message: either an event or the final result.
type RunTurnResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*RunTurnResponse_Event
	//	*RunTurnResponse_Result
	Msg           isRunTurnResponse_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunTurnResponse) Reset() {
	*x = RunTurnResponse{}
	mi := &file_proto_agentary_v1_runtime_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunTurnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunTurnResponse) ProtoMessage() {}

func (x *RunTurnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentary_v1_runtime_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunTurnResponse.ProtoReflect.Descriptor instead.
func (*RunTurnResponse) Descriptor() ([]byte, []int) {
	return file_proto_agentary_v1_runtime_proto_rawDescGZIP(), []int{3}
}

func (x *RunTurnResponse) GetMsg() isRunTurnResponse_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *RunTurnResponse) GetEvent() *Event {
	if x != nil {
		if x, ok := x.Msg.(*RunTurnResponse_Event); ok {
			return x.Event
		}
	}
	return nil
}

func (x *RunTurnResponse) GetResult() *TurnResult {
	if x != nil {
		if x, ok := x.Msg.(*RunTurnResponse_Result); ok {
			return x.Result
		}
	}
	return nil
}

type isRunTurnResponse_Msg interface {
	isRunTurnResponse_Msg()
}

type RunTurnResponse_Event struct {
	Event *Event `protobuf:"bytes,1,opt,name=event,proto3,oneof"`
}

type RunTurnResponse_Result struct {
	Result *TurnResult `protobuf:"bytes,2,opt,name=result,proto3,oneof"`
}

func (*RunTurnResponse_Event) isRunTurnResponse_Msg() {}

func (*RunTurnResponse_Result) isRunTurnResponse_Msg() {}

var File_proto_agentary_v1_runtime_proto protoreflect.FileDescriptor

const file_proto_agentary_v1_runtime_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/agentary/v1/runtime.proto\x12\x13agentary.runtime.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd9\x01\n" +
	"\vTurnRequest\x12\x12\n" +
	"\x04team\x18\x01 \x01(\tR\x04team\x12\x14\n" +
	"\x05agent\x18\x02 \x01(\tR\x05agent\x12\x1c\n" +
	"\atask_id\x18\x03 \x01(\x03H\x00R\x06taskId\x88\x01\x01\x12\x14\n" +
	"\x05input\x18\x04 \x01(\tR\x05input\x12+\n" +
	"\x11network_allowlist\x18\x05 \x03(\tR\x10networkAllowlist\x12\x14\n" +
	"\x05model\x18\x06 \x01(\tR\x05model\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\a \x01(\x05R\tmaxTokensB\n" +
	"\n" +
	"\b_task_id\"\xd6\x01\n" +
	"\x05Event\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04team\x18\x02 \x01(\tR\x04team\x12\x14\n" +
	"\x05agent\x18\x03 \x01(\tR\x05agent\x12\x1c\n" +
	"\atask_id\x18\x04 \x01(\x03H\x00R\x06taskId\x88\x01\x01\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12+\n" +
	"\x04data\x18\x06 \x01(\v2\x17.google.protobuf.StructR\x04dataB\n" +
	"\n" +
	"\b_task_id\"$\n" +
	"\n" +
	"TurnResult\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output\"\x87\x01\n" +
	"\x0fRunTurnResponse\x122\n" +
	"\x05event\x18\x01 \x01(\v2\x1a.agentary.runtime.v1.EventH\x00R\x05event\x129\n" +
	"\x06result\x18\x02 \x01(\v2\x1f.agentary.runtime.v1.TurnResultH\x00R\x06resultB\x05\n" +
	"\x03msg2c\n" +
	"\fAgentRuntime\x12S\n" +
	"\aRunTurn\x12 .agentary.runtime.v1.TurnRequest\x1a$.agentary.runtime.v1.RunTurnResponse0\x01BFZDgithub.com/ankittk/agentary/internal/agent/runtime/grpc/pb;pbruntimeb\x06proto3"

var (
	file_proto_agentary_v1_runtime_proto_rawDescOnce sync.Once
	file_proto_agentary_v1_runtime_proto_rawDescData []byte
)

func file_proto_agentary_v1_runtime_proto_rawDescGZIP() []byte {
	file_proto_agentary_v1_runtime_proto_rawDescOnce.Do(func() {
		file_proto_agentary_v1_runtime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agentary_v1_runtime_proto_rawDesc), len(file_proto_agentary_v1_runtime_proto_rawDesc)))
	})
	return file_proto_agentary_v1_runtime_proto_rawDescData
}

var file_proto_agentary_v1_runtime_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_agentary_v1_runtime_proto_goTypes = []any{
	(*TurnRequest)(nil),           // 0: agentary.runtime.v1.TurnRequest
	(*Event)(nil),                 // 1: agentary.runtime.v1.Event
	(*TurnResult)(nil),            // 2: agentary.runtime.v1.TurnResult
	(*RunTurnResponse)(nil),       // 3: agentary.runtime.v1.RunTurnResponse
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 5: google.protobuf.Struct
}
var file_proto_agentary_v1_runtime_proto_depIdxs = []int32{
	4, // 0: agentary.runtime.v1.Event.timestamp:type_name -> google.protobuf.Timestamp
	5, // 1: agentary.runtime.v1.Event.data:type_name -> google.protobuf.Struct
	1, // 2: agentary.runtime.v1.RunTurnResponse.event:type_name -> agentary.runtime.v1.Event
	2, // 3: agentary.runtime.v1.RunTurnResponse.result:type_name -> agentary.runtime.v1.TurnResult
	0, // 4: agentary.runtime.v1.AgentRuntime.RunTurn:input_type -> agentary.runtime.v1.TurnRequest
	3, // 5: agentary.runtime.v1.AgentRuntime.RunTurn:output_type -> agentary.runtime.v1.RunTurnResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_agentary_v1_runtime_proto_init() }
func file_proto_agentary_v1_runtime_proto_init() {
	if File_proto_agentary_v1_runtime_proto != nil {
		return
	}
	file_proto_agentary_v1_runtime_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_agentary_v1_runtime_proto_msgTypes[1].OneofWrappers = []any{}
	file_proto_agentary_v1_runtime_proto_msgTypes[3].OneofWrappers = []any{
		(*RunTurnResponse_Event)(nil),
		(*RunTurnResponse_Result)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agentary_v1_runtime_proto_rawDesc), len(file_proto_agentary_v1_runtime_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_agentary_v1_runtime_proto_goTypes,
		DependencyIndexes: file_proto_agentary_v1_runtime_proto_depIdxs,
		MessageInfos:      file_proto_agentary_v1_runtime_proto_msgTypes,
	}.Build()
	File_proto_agentary_v1_runtime_proto = out.File
	file_proto_agentary_v1_runtime_proto_goTypes = nil
	file_proto_agentary_v1_runtime_proto_depIdxs = nil
}
