// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.30.2
// source: proto/agentary/v1/runtime.proto

package pbruntime

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentRuntime_RunTurn_FullMethodName = "/agentary.runtime.v1.AgentRuntime/RunTurn"
)

// AgentRuntimeClient is the client API for AgentRuntime service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentRuntime runs a single agent turn: request in, stream of events and final result.
type AgentRuntimeClient interface {
	// RunTurn runs one agent turn. Server streams events then sends a final result.
	RunTurn(ctx context.Context, in *TurnRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RunTurnResponse], error)
}

type agentRuntimeClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentRuntimeClient(cc grpc.ClientConnInterface) AgentRuntimeClient {
	return &agentRuntimeClient{cc}
}

func (c *agentRuntimeClient) RunTurn(ctx context.Context, in *TurnRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RunTurnResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentRuntime_ServiceDesc.Streams[0], AgentRuntime_RunTurn_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TurnRequest, RunTurnResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentRuntime_RunTurnClient = grpc.ServerStreamingClient[RunTurnResponse]

// AgentRuntimeServer is the server API for AgentRuntime service.
// All implementations must embed UnimplementedAgentRuntimeServer
// for forward compatibility.
//
// AgentRuntime runs a single agent turn: request in, stream of events and final result.
type AgentRuntimeServer interface {
	// RunTurn runs one agent turn. Server streams events then sends a final result.
	RunTurn(*TurnRequest, grpc.ServerStreamingServer[RunTurnResponse]) error
	mustEmbedUnimplementedAgentRuntimeServer()
}

// UnimplementedAgentRuntimeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentRuntimeServer struct{}

func (UnimplementedAgentRuntimeServer) RunTurn(*TurnRequest, grpc.ServerStreamingServer[RunTurnResponse]) error {
	return status.Error(codes.Unimplemented, "method RunTurn not implemented")
}
func (UnimplementedAgentRuntimeServer) mustEmbedUnimplementedAgentRuntimeServer() {}
func (UnimplementedAgentRuntimeServer) testEmbeddedByValue()                      {}

// UnsafeAgentRuntimeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentRuntimeServer will
// result in compilation errors.
type UnsafeAgentRuntimeServer interface {
	mustEmbedUnimplementedAgentRuntimeServer()
}

func RegisterAgentRuntimeServer(s grpc.ServiceRegistrar, srv AgentRuntimeServer) {
	// If the following call panics, it indicates UnimplementedAgentRuntimeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentRuntime_ServiceDesc, srv)
}

func _AgentRuntime_RunTurn_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TurnRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentRuntimeServer).RunTurn(m, &grpc.GenericServerStream[TurnRequest, RunTurnResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentRuntime_RunTurnServer = grpc.ServerStreamingServer[RunTurnResponse]

// AgentRuntime_ServiceDesc is the grpc.ServiceDesc for AgentRuntime service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentRuntime_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agentary.runtime.v1.AgentRuntime",
	HandlerType: (*AgentRuntimeServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RunTurn",
			Handler:       _AgentRuntime_RunTurn_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/agentary/v1/runtime.proto",
}
